
language: python
python:
 - "3.9"
 - "2.2"
 env:
  - DJANGO_VERSION=4.1.2
 install: "pip install -r requirements.txt"
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
  script:
  
